######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 4 16:49:29 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
